services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    FormBuilderBundle\Document\Areabrick\Form\FormDialogBuilder:
        arguments:
            $translator: '@Pimcore\Bundle\AdminBundle\Translation\AdminUserTranslator'

    FormBuilderBundle\Document\Areabrick\Form\Form:
        tags:
            - { name: pimcore.area.brick, id: formbuilder_form }