services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # alias for form builder subscriber.
    FormBuilderBundle\EventSubscriber\FormBuilderSubscriber: ~