services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FormBuilderBundle\Repository\FormDefinitionRepositoryInterface: '@FormBuilderBundle\Repository\FormDefinitionRepository'
    FormBuilderBundle\Repository\FormDefinitionRepository: ~

    FormBuilderBundle\Repository\OutputWorkflowRepositoryInterface: '@FormBuilderBundle\Repository\OutputWorkflowRepository'
    FormBuilderBundle\Repository\OutputWorkflowRepository: ~

    FormBuilderBundle\Repository\DoubleOptInSessionRepositoryInterface: '@FormBuilderBundle\Repository\DoubleOptInSessionRepository'
    FormBuilderBundle\Repository\DoubleOptInSessionRepository: ~