services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    FormBuilderBundle\Registry\RuntimeDataProviderRegistry: ~

    FormBuilderBundle\Form\RuntimeData\FormRuntimeDataAllocator: ~
    FormBuilderBundle\Form\RuntimeData\FormRuntimeDataAllocatorInterface: '@FormBuilderBundle\Form\RuntimeData\FormRuntimeDataAllocator'

    FormBuilderBundle\Form\RuntimeData\Provider\DoubleOptInSessionDataProvider:
        tags:
            - { name: form_builder.runtime_data_provider }
