services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    FormBuilderBundle\Validation\ConditionalLogic\Rule\Condition\ElementValueCondition: ~

    FormBuilderBundle\Validation\ConditionalLogic\Rule\Condition\OutputWorkflowCondition: ~