FormBuilderBundle\Model\DoubleOptInSession:
    type: entity
    table: formbuilder_double_opt_in_session
    indexes:
        token_form:
            columns: [ token, form_definition, applied ]
    id:
        token:
            unique: true
            column: token
            type: uuid
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator
    fields:
        email:
            column: email
            type: string
            nullable: false
            length: 190
        additionalData:
            column: additional_data
            type: array
            nullable: true
        dispatchLocation:
            column: dispatch_location
            type: text
            nullable: true
        applied:
            column: applied
            type: boolean
            options:
                default: 0
        creationDate:
            column: creationDate
            type: datetime
            nullable: false
    manyToOne:
        formDefinition:
            targetEntity: FormBuilderBundle\Model\FormDefinition
            orphanRemoval: true
            joinColumn:
                name: form_definition
                referencedColumnName: id
                onDelete: CASCADE