#!/usr/bin/env bash

export DACHCOM_BUNDLE_HOME=$TRAVIS_BUILD_DIR
export DACHCOM_BUNDLE_NAME="FormBuilder"
export DACHCOM_BUNDLE_REPO_NAME="formbuilder"
export DACHCOM_BUNDLE_COMMIT=$TRAVIS_COMMIT
export DACHCOM_BUNDLE_BRANCH=$TRAVIS_BRANCH

export DACHCOM_BUNDLE_CLASS='FormBuilderBundle\FormBuilderBundle'
export DACHCOM_BUNDLE_INSTALLER_CLASS='FormBuilderBundle\Tool\Install'

declare -A DACHCOM_INSTALL_CONFIG_FILES=(
 ["$DACHCOM_BUNDLE_HOME/etc/config/bundle/extensions.template.php"]="var/config/extensions.php"
 ["$DACHCOM_BUNDLE_HOME/etc/config/bundle/system.template.php"]="var/config/system.php"
)