services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    FormBuilderBundle\MailEditor\Widget\FormFieldWidget:
        tags:
            - { name: form_builder.mail_editor.widget, type: fb_field }

    FormBuilderBundle\MailEditor\Widget\DateWidget:
        tags:
            - { name: form_builder.mail_editor.widget, type: date }