form_builder:
    types:
        checkbox:
            class: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            backend:
                form_type_group: other_fields
                label: 'form_builder_type.checkbox_type'
                icon_class: 'form_builder_icon_checkbox'
                constraints:
                    disabled:
                        - 'dynamic_multi_file_not_blank'
                output_workflow:
                    object:
                        allowed_class_types:
                            - checkbox
                fields:
                    options.value:
                        display_group_id: base
                        type: textfield
                        label: 'form_builder_type_field_base.value'
                        config:
                            disabled: true
                            data: '1'
                    options.data:
                        display_group_id: base
                        type: checkbox
                        label: 'form_builder_type_field_base.data'
                        config: ~