form_builder:
    types:
        hidden:
            class: Symfony\Component\Form\Extension\Core\Type\HiddenType
            backend:
                form_type_group: hidden_fields
                label: 'form_builder_type.hidden_type'
                icon_class: 'form_builder_icon_hidden'
                constraints: false
                output_workflow:
                    object:
                        allowed_class_types:
                            - input
                            - textarea
                            - wysiwyg
                fields:
                    options.value: ~
                    options.help_text: ~