form_builder:
    types:
        time:
            class: Symfony\Component\Form\Extension\Core\Type\TimeType
            output_transformer: date_transformer
            backend:
                form_type_group: date_time_fields
                label: 'form_builder_type.time_type'
                icon_class: 'form_builder_icon_time'
                constraints:
                    disabled:
                        - 'dynamic_multi_file_not_blank'
                output_workflow:
                    object:
                        allowed_class_types:
                            - time
                fields:
                    options.data: ~
                    options.value: ~
                    options.widget:
                        display_group_id: attributes
                        type: select
                        label: 'form_builder_type_field.date_widget'
                        config:
                            options:
                                - ['Choice', 'choice']
                                - ['Text', 'text']
                                - ['Single Text', 'single_text']
                    options.seconds:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.date_seconds'
                        config: ~
                    options.minutes:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.date_minutes'
                        config: ~
                    options.hours:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.date_hours'
                        config: ~
                    options.with_minutes:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.date_with_minutes'
                    options.with_seconds:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.date_with_seconds'
        birthday:
            class: Symfony\Component\Form\Extension\Core\Type\BirthdayType
            backend:
                form_type_group: date_time_fields
                label: 'form_builder_type.birthday_type'
                icon_class: 'form_builder_icon_birthday'
                constraints:
                    disabled:
                        - 'dynamic_multi_file_not_blank'
                fields:
                    options.data: ~
                    options.value: ~