FormBuilderBundle\Event\OutputWorkflow\OutputWorkflowSignalEvent:
    attributes:
        name:
            groups: [Default, OutputWorkflow]
        data:
            groups: [Default, OutputWorkflow]
