#!/bin/bash
set -e

echo "START CODECEPTION TESTS FOR $DACHCOM_BUNDLE_NAME"

CMD="phpdbg -qrr vendor/bin/codecept run -c lib/$DACHCOM_BUNDLE_NAME --env travis"

# generate json result file
CMD="$CMD --json"

echo $CMD
eval $CMD
