services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FormBuilderBundle\Registry\OptionsTransformerRegistry:
        arguments:
            $optionsInterface: 'FormBuilderBundle\Transformer\OptionsTransformerInterface'
            $dynamicOptionsInterface: 'FormBuilderBundle\Transformer\DynamicOptionsTransformerInterface'

    FormBuilderBundle\Transformer\ChoicesTransformer:
        tags:
            - {name: form_builder.transformer.options}

    FormBuilderBundle\Transformer\DefaultValueTransformer:
        tags:
            - {name: form_builder.transformer.options}

    FormBuilderBundle\Transformer\HrefTransformer:
        tags:
            - {name: form_builder.transformer.options}

    FormBuilderBundle\Transformer\ChoicesMetaTransformer:
        tags:
            - {name: form_builder.transformer.dynamic_options}
