# Frontend Routing
form_builder.controller.funnel.dispatch:
    path: /{_locale}/fb/funnel/{funnelId}/{channelId}/{storageToken}
    controller: FormBuilderBundle\Controller\FunnelController::dispatchAction
    methods: [POST, GET]