services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    FormBuilderBundle\Assembler\FormAssembler: ~
    FormBuilderBundle\Assembler\FunnelActionElementAssembler: ~