services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # form builder
    FormBuilderBundle\Builder\FrontendFormBuilder: ~

    # backend form builder
    FormBuilderBundle\Builder\ExtJsFormBuilder: ~

    # form values output applier
    FormBuilderBundle\Form\FormValuesOutputApplier: ~
    FormBuilderBundle\Form\FormValuesOutputApplierInterface: '@FormBuilderBundle\Form\FormValuesOutputApplier'

    # error serializer
    FormBuilderBundle\Form\FormErrorsSerializer: ~
    FormBuilderBundle\Form\FormErrorsSerializerInterface: '@FormBuilderBundle\Form\FormErrorsSerializer'

    # form data connector
    FormBuilderBundle\Form\Data\Connector\FormDataConnectorInterface: '@FormBuilderBundle\Form\Data\Connector\FormDataConnector'
    FormBuilderBundle\Form\Data\Connector\FormDataConnector: ~