services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # form builder
    FormBuilderBundle\Form\Builder: ~

    # backend form builder
    FormBuilderBundle\Backend\Form\Builder: ~

    # backend output workflow builder
    FormBuilderBundle\Backend\OutputWorkflow\Builder:

    # form values output applier
    FormBuilderBundle\Form\FormValuesOutputApplier: ~
    FormBuilderBundle\Form\FormValuesOutputApplierInterface: '@FormBuilderBundle\Form\FormValuesOutputApplier'

    # error serializer
    FormBuilderBundle\Form\FormErrorsSerializer: ~
    FormBuilderBundle\Form\FormErrorsSerializerInterface: '@FormBuilderBundle\Form\FormErrorsSerializer'

    # form data connector
    FormBuilderBundle\Storage\DataConnector\FormDataConnectorInterface: '@FormBuilderBundle\Storage\DataConnector\FormDataConnector'
    FormBuilderBundle\Storage\DataConnector\FormDataConnector: ~