services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # form builder
    FormBuilderBundle\Form\Builder: ~

    # backend form builder
    FormBuilderBundle\Backend\Form\Builder: ~

    # form values output applier
    FormBuilderBundle\Form\FormValuesOutputApplier: ~
    FormBuilderBundle\Form\FormValuesOutputApplierInterface: '@FormBuilderBundle\Form\FormValuesOutputApplier'

    # error serializer
    FormBuilderBundle\Form\FormErrorsSerializer: ~
    FormBuilderBundle\Form\FormErrorsSerializerInterface: '@FormBuilderBundle\Form\FormErrorsSerializer'
