services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FormBuilderBundle\Factory\FormDataFactoryInterface: '@FormBuilderBundle\Factory\FormDataFactory'
    FormBuilderBundle\Factory\FormDataFactory: ~

    FormBuilderBundle\Factory\FormDefinitionFactoryInterface:
        alias: FormBuilderBundle\Factory\FormDefinitionFactory
        public: true

    FormBuilderBundle\Factory\FormDefinitionFactory: ~

    FormBuilderBundle\Factory\OutputWorkflowFactoryInterface: '@FormBuilderBundle\Factory\OutputWorkflowFactory'
    FormBuilderBundle\Factory\OutputWorkflowFactory: ~

    FormBuilderBundle\Factory\ObjectResolverFactoryInterface: '@FormBuilderBundle\Factory\ObjectResolverFactory'
    FormBuilderBundle\Factory\ObjectResolverFactory: ~