services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FormBuilderBundle\Factory\FormDataFactoryInterface: '@FormBuilderBundle\Factory\FormDataFactory'
    FormBuilderBundle\Factory\FormDataFactory: ~

    FormBuilderBundle\Factory\FormDefinitionFactoryInterface: '@FormBuilderBundle\Factory\FormDefinitionFactory'
    FormBuilderBundle\Factory\FormDefinitionFactory: ~

    FormBuilderBundle\Factory\OutputWorkflowFactoryInterface: '@FormBuilderBundle\Factory\OutputWorkflowFactory'
    FormBuilderBundle\Factory\OutputWorkflowFactory: ~

    FormBuilderBundle\Factory\ObjectResolverFactoryInterface: '@FormBuilderBundle\Factory\ObjectResolverFactory'
    FormBuilderBundle\Factory\ObjectResolverFactory: ~