services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # factory: form
    FormBuilderBundle\Factory\FormFactoryInterface: '@FormBuilderBundle\Factory\FormFactory'
    FormBuilderBundle\Factory\FormFactory: ~

    # factory: output workflow
    FormBuilderBundle\Factory\OutputWorkflowFactoryInterface: '@FormBuilderBundle\Factory\OutputWorkflowFactory'
    FormBuilderBundle\Factory\OutputWorkflowFactory: ~