services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

     # stream: files
    FormBuilderBundle\Stream\FileStreamInterface: '@FormBuilderBundle\Stream\FileStream'
    FormBuilderBundle\Stream\FileStream: ~

     # stream: attachment
    FormBuilderBundle\Stream\AttachmentStreamInterface: '@FormBuilderBundle\Stream\AttachmentStream'
    FormBuilderBundle\Stream\AttachmentStream: ~